/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examples.com.intelligt.modbus.examples;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.general.DatasetUtilities;
import org.jfree.data.xy.XYDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author proxc
 */
public class Home16 extends javax.swing.JFrame {

    /**
     * Creates new form Home16
     */
    public Home16() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_chart = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_north2 = new javax.swing.JLabel();
        lbl_north1 = new javax.swing.JLabel();
        lbl_north4 = new javax.swing.JLabel();
        lbl_north3 = new javax.swing.JLabel();
        lbl_north5 = new javax.swing.JLabel();
        lbl_north6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        pnl_chart.setBackground(new java.awt.Color(255, 255, 255));
        pnl_chart.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnl_chartMouseDragged(evt);
            }
        });
        pnl_chart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_chartMousePressed(evt);
            }
        });
        pnl_chart.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(34, 41, 50));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("X  ");
        jLabel1.setOpaque(true);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        pnl_chart.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 996, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examples/com/intelligt/modbus/examples/Steam Logo with iso.png"))); // NOI18N
        pnl_chart.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 300, 190));

        lbl_north2.setBackground(new java.awt.Color(48, 201, 235));
        lbl_north2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_north2.setForeground(new java.awt.Color(0, 0, 51));
        lbl_north2.setText("One stop solutions for Analysis and Sampling systems in Liquid, Gas and Ambient Air");
        lbl_north2.setToolTipText("");
        lbl_north2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_north2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_north2MousePressed(evt);
            }
        });

        lbl_north1.setBackground(new java.awt.Color(48, 201, 235));
        lbl_north1.setFont(new java.awt.Font("Segoe UI", 0, 58)); // NOI18N
        lbl_north1.setForeground(new java.awt.Color(255, 0, 0));
        lbl_north1.setText("STEAM EQUIPMENTS PVT LTD.");
        lbl_north1.setToolTipText("");
        lbl_north1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_north1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_north1MousePressed(evt);
            }
        });

        lbl_north4.setBackground(new java.awt.Color(48, 201, 235));
        lbl_north4.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        lbl_north4.setForeground(new java.awt.Color(51, 0, 153));
        lbl_north4.setText("     Welcomes you to ");
        lbl_north4.setToolTipText("");
        lbl_north4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_north4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_north4MousePressed(evt);
            }
        });

        lbl_north3.setBackground(new java.awt.Color(48, 201, 235));
        lbl_north3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lbl_north3.setForeground(new java.awt.Color(102, 102, 102));
        lbl_north3.setText("Data Aquisition Software and");
        lbl_north3.setToolTipText("");
        lbl_north3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_north3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_north3MousePressed(evt);
            }
        });

        lbl_north5.setBackground(new java.awt.Color(48, 201, 235));
        lbl_north5.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lbl_north5.setForeground(new java.awt.Color(102, 102, 102));
        lbl_north5.setText("Realtime Display");
        lbl_north5.setToolTipText("");
        lbl_north5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_north5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_north5MousePressed(evt);
            }
        });

        lbl_north6.setBackground(new java.awt.Color(48, 201, 235));
        lbl_north6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_north6.setForeground(new java.awt.Color(0, 0, 51));
        lbl_north6.setText("Shelter based Steam & Water Analysis System, CEMS, AAQMS, EQMS, WQMS ");
        lbl_north6.setToolTipText("");
        lbl_north6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_north6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_north6MousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("\"");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setText("\"");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(385, 385, 385)
                        .addComponent(lbl_north4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(lbl_north1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(lbl_north3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(lbl_north5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_north2, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(lbl_north6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(pnl_chart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_chart, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_north1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_north4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_north3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_north5)
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_north2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_north6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnl_chartMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_chartMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_pnl_chartMousePressed

    private void pnl_chartMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_chartMouseDragged
        // TODO add your handling code here:


    }//GEN-LAST:event_pnl_chartMouseDragged

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
       

        String MacId = LicenseKey.getMacID();
        System.out.println("MacId=" + MacId);

        String Chavi_for_Soft = null;
        Chavi_for_Soft = KeyMain.encrypt(MacId);
        System.out.println("Chavi_for_Soft=");
        System.out.println(Chavi_for_Soft);
        System.out.println("RGFuaXNoW0JAMWI3ZGE0ZA==");

        if (KeyMain.decrypt(Chavi_for_Soft).equals(MacId)) {
            dispose();
            java.awt.EventQueue.invokeLater(new Runnable() {
                @Override
                public void run() {
                    new ActivatedScreen().setVisible(true);
                }
            });
        } else {
            JOptionPane.showMessageDialog(null, "Invalid Key", "License Error", JOptionPane.ERROR_MESSAGE);
            dispose();
            System.exit(0);

        }

    }//GEN-LAST:event_jLabel1MousePressed

    private void lbl_north1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_north1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_north1MousePressed

    private void lbl_north2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_north2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_north2MousePressed

    private void lbl_north4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_north4MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_north4MousePressed

    private void lbl_north3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_north3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_north3MousePressed

    private void lbl_north5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_north5MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_north5MousePressed

    private void lbl_north6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_north6MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_north6MousePressed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        dispose();

        //      Home16.setDefaultCloseOperation(Home16.HIDE_ON_CLOSE);
        //frame1.exit(0);
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainForm().setVisible(true);
            }
        });

    }//GEN-LAST:event_formMouseClicked

    //Let's add a chart to top Jpanel
    //We are going to use JfreeCharts
    //Source will be 
    //Ofcourse before doing anything else you need to download JfreeCharts Lib and import into your project
    /*    private XYDataset createDataset2() {
        XYSeriesCollection dataset = new XYSeriesCollection();
        XYSeries series1 = new XYSeries("Object 1");
        XYSeries series2 = new XYSeries("Object 2");
        XYSeries series3 = new XYSeries("Object 3");

        series1.add(1.0, 2.0);
        series1.add(2.0, 3.0);
        series1.add(3.0, 2.5);
        series1.add(3.5, 2.8);
        series1.add(4.2, 6.0);

        series2.add(2.0, 1.0);
        series2.add(2.5, 2.4);
        series2.add(3.2, 1.2);
        series2.add(3.9, 2.8);
        series2.add(4.6, 3.0);

        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        series3.add(1.2, 4.0);
        series3.add(2.5, 4.4);
        series3.add(3.8, 4.2);
        series3.add(4.3, 3.8);
        series3.add(4.5, 4.0);

        dataset.addSeries(series1);
        dataset.addSeries(series2);
        dataset.addSeries(series3);

        return dataset;
    }
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home16().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbl_north1;
    private javax.swing.JLabel lbl_north2;
    private javax.swing.JLabel lbl_north3;
    private javax.swing.JLabel lbl_north4;
    private javax.swing.JLabel lbl_north5;
    private javax.swing.JLabel lbl_north6;
    private javax.swing.JPanel pnl_chart;
    // End of variables declaration//GEN-END:variables
}
